import type { CommunityDashboardData } from "./types";

/** Demo dataset for ZIP 91001 — no PII */
export const mockCommunity91001: CommunityDashboardData = {
  zip: "91001",
  stats: {
    registeredHouseholds: 25,
    pets: 9,
    transportationNeeds: 7,
    medicalPowerNeeds: 4,
    markedSafe: 8,
    requestedHelp: 6,
    volunteers: 6,
    averagePreparedness: 55,
  },
  households: [
    {
      anonymous_id: "A7F2",
      zip_code: "91001",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 40,
    },
    {
      anonymous_id: "C19B",
      zip_code: "91001",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: true,
      status: "Safe",
      prep_score: 80,
    },
    {
      anonymous_id: "B92K",
      zip_code: "91001",
      has_pets: true,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Preparing",
      prep_score: 55,
    },
    {
      anonymous_id: "E51M",
      zip_code: "91001",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Shelter info",
      prep_score: 35,
    },
    {
      anonymous_id: "D33Q",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: true,
      can_volunteer: false,
      status: "Medical device power support",
      prep_score: 50,
    },
    {
      anonymous_id: "F88R",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 32,
    },
    {
      anonymous_id: "G02P",
      zip_code: "91001",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: true,
      status: "Preparing",
      prep_score: 65,
    },
    {
      anonymous_id: "H44T",
      zip_code: "91001",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Safe",
      prep_score: 75,
    },
    {
      anonymous_id: "J19W",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: true,
      can_volunteer: false,
      status: "Medical device power support",
      prep_score: 45,
    },
    {
      anonymous_id: "K77S",
      zip_code: "91001",
      has_pets: true,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Shelter info",
      prep_score: 42,
    },
    {
      anonymous_id: "L03V",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: true,
      status: "Safe",
      prep_score: 88,
    },
    {
      anonymous_id: "M56X",
      zip_code: "91001",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 38,
    },
    {
      anonymous_id: "N91Y",
      zip_code: "91001",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: true,
      status: "Preparing",
      prep_score: 72,
    },
    {
      anonymous_id: "P24Z",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Requested help",
      prep_score: 28,
    },
    {
      anonymous_id: "Q67A",
      zip_code: "91001",
      has_pets: true,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Safe",
      prep_score: 68,
    },
    {
      anonymous_id: "R08B",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Shelter info",
      prep_score: 48,
    },
    {
      anonymous_id: "S33C",
      zip_code: "91001",
      has_pets: true,
      has_transport: false,
      medical_needs: true,
      can_volunteer: false,
      status: "Medical device power support",
      prep_score: 52,
    },
    {
      anonymous_id: "T49D",
      zip_code: "91001",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Safe",
      prep_score: 58,
    },
    {
      anonymous_id: "U15E",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: true,
      status: "Safe",
      prep_score: 82,
    },
    {
      anonymous_id: "V72F",
      zip_code: "91001",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Requested help",
      prep_score: 44,
    },
    {
      anonymous_id: "W28G",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 36,
    },
    {
      anonymous_id: "Y04J",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: true,
      can_volunteer: false,
      status: "Medical device power support",
      prep_score: 41,
    },
    {
      anonymous_id: "Z12K",
      zip_code: "91001",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Safe",
      prep_score: 77,
    },
    {
      anonymous_id: "K8LM",
      zip_code: "91001",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: true,
      status: "Safe",
      prep_score: 85,
    },
    {
      anonymous_id: "R50N",
      zip_code: "91001",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 33,
    },
  ],
  needs: [
    { label: "Evacuation rides", count: 7 },
    { label: "Water delivery", count: 5 },
    { label: "Accessible shelter beds", count: 3 },
    { label: "Medical device power support", count: 4 },
    { label: "Pet transport", count: 4 },
    { label: "Translation help", count: 2 },
    { label: "Oxygen tank refills", count: 2 },
    { label: "Volunteer driver matches", count: 5 },
    { label: "Marked safe", count: 8 },
    { label: "Prescription pickup", count: 3 },
    { label: "Large animal boarding", count: 2 },
    { label: "Ice / cooling centers", count: 3 },
    { label: "Shelter info", count: 6 },
    { label: "Accessible evacuation rides", count: 3 },
    { label: "N95 / smoke masks", count: 4 },
    { label: "Infant supplies", count: 2 },
    { label: "Elder check-in requests", count: 2 },
    { label: "Phone charging stations", count: 3 },
  ],
  events: [
    {
      id: "e1",
      message: "Household R50N requested evacuation transport",
      timestamp: "2026-05-09T18:22:00.000Z",
    },
    {
      id: "e2",
      message: "Household K8LM volunteered for neighborhood transport",
      timestamp: "2026-05-09T18:15:00.000Z",
    },
    {
      id: "e3",
      message: "Household A7F2 requested evacuation transport",
      timestamp: "2026-05-09T18:02:00.000Z",
    },
    {
      id: "e4",
      message: "Household Z12K marked safe",
      timestamp: "2026-05-09T17:58:00.000Z",
    },
    {
      id: "e5",
      message: "Household C19B marked safe",
      timestamp: "2026-05-09T17:45:00.000Z",
    },
    {
      id: "e6",
      message: "Household Y04J requested medical device power support",
      timestamp: "2026-05-09T17:40:00.000Z",
    },
    {
      id: "e7",
      message: "Household B92K completed go-bag task",
      timestamp: "2026-05-09T17:20:00.000Z",
    },
    {
      id: "e8",
      message: "Household G02P completed prep task",
      timestamp: "2026-05-09T17:05:00.000Z",
    },
    {
      id: "e9",
      message: "Household E51M asked for pet shelter info",
      timestamp: "2026-05-09T16:55:00.000Z",
    },
    {
      id: "e10",
      message: "Household K77S asked for shelter routing info",
      timestamp: "2026-05-09T16:48:00.000Z",
    },
    {
      id: "e11",
      message: "Household D33Q requested medical device power support",
      timestamp: "2026-05-09T16:30:00.000Z",
    },
    {
      id: "e12",
      message: "Household P24Z requested help (general)",
      timestamp: "2026-05-09T16:12:00.000Z",
    },
    {
      id: "e13",
      message: "Household N91Y volunteered for welfare check-ins",
      timestamp: "2026-05-09T15:45:00.000Z",
    },
    {
      id: "e14",
      message: "Household C19B volunteered for neighborhood transport",
      timestamp: "2026-05-09T15:10:00.000Z",
    },
    {
      id: "e15",
      message: "Household L03V marked safe",
      timestamp: "2026-05-09T14:55:00.000Z",
    },
    {
      id: "e16",
      message: "Household M56X requested evacuation transport",
      timestamp: "2026-05-09T14:30:00.000Z",
    },
    {
      id: "e17",
      message: "Household U15E volunteered for supply drop coordination",
      timestamp: "2026-05-09T13:50:00.000Z",
    },
    {
      id: "e18",
      message: "Household V72F requested help (general)",
      timestamp: "2026-05-09T13:20:00.000Z",
    },
    {
      id: "e19",
      message: "Household W28G requested evacuation transport",
      timestamp: "2026-05-08T22:10:00.000Z",
    },
    {
      id: "e20",
      message: "Household F88R requested evacuation transport",
      timestamp: "2026-05-08T21:40:00.000Z",
    },
  ],
  resources: [
    {
      id: "r1",
      title: "County emergency hotline",
      description: "Official evacuation orders and shelter openings.",
      detail:
        "Call your county OES number or 2-1-1 for verified shelter locations.",
    },
    {
      id: "r2",
      title: "Pet-friendly shelter lookup",
      description:
        "Aggregate shelter capacity by ZIP — no personal data required.",
      detail:
        "Check Red Cross / county animal services for co-sheltering options.",
    },
    {
      id: "r3",
      title: "Community transport coordination",
      description: "Volunteers matched at neighborhood level only.",
      detail: "Sign up via SMS; dashboard shows counts, not rider identities.",
    },
    {
      id: "r4",
      title: "Go-bag checklist (SMS)",
      description: "Text PREP for a short checklist; reply DONE with task numbers.",
      detail:
        "Progress updates community preparedness scores anonymously.",
    },
    {
      id: "r5",
      title: "Medical device power bank loan",
      description: "Short-term battery packs for CPAP and similar devices.",
      detail:
        "Pickup hubs listed by ZIP; return when grid status is restored.",
    },
    {
      id: "r6",
      title: "Cooling center map",
      description: "Hours and capacity for heat-relief locations.",
      detail: "Updated from county public health; accessibility notes included.",
    },
    {
      id: "r7",
      title: "Multi-language alert digest",
      description: "Machine-translated summaries of official alerts.",
      detail: "Not a substitute for official sources; links back to primary feeds.",
    },
    {
      id: "r8",
      title: "Neighborhood wellness check script",
      description: "Short SMS prompts for block-level check-ins.",
      detail: "Volunteers log counts only — no names stored on the dashboard.",
    },
  ],
};

/** Smaller demo ZIP for multi-area testing */
export const mockCommunity92105: CommunityDashboardData = {
  zip: "92105",
  stats: {
    registeredHouseholds: 12,
    pets: 5,
    transportationNeeds: 3,
    medicalPowerNeeds: 2,
    markedSafe: 4,
    requestedHelp: 2,
    volunteers: 3,
    averagePreparedness: 58,
  },
  households: [
    {
      anonymous_id: "N3XP",
      zip_code: "92105",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 45,
    },
    {
      anonymous_id: "Q8WR",
      zip_code: "92105",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: true,
      status: "Safe",
      prep_score: 90,
    },
    {
      anonymous_id: "T2LS",
      zip_code: "92105",
      has_pets: true,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Preparing",
      prep_score: 62,
    },
    {
      anonymous_id: "V9KM",
      zip_code: "92105",
      has_pets: false,
      has_transport: false,
      medical_needs: true,
      can_volunteer: false,
      status: "Medical device power support",
      prep_score: 51,
    },
    {
      anonymous_id: "X1HJ",
      zip_code: "92105",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Shelter info",
      prep_score: 37,
    },
    {
      anonymous_id: "Z4PC",
      zip_code: "92105",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: true,
      status: "Safe",
      prep_score: 78,
    },
    {
      anonymous_id: "B6DF",
      zip_code: "92105",
      has_pets: false,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Requested help",
      prep_score: 29,
    },
    {
      anonymous_id: "D7MN",
      zip_code: "92105",
      has_pets: true,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Safe",
      prep_score: 71,
    },
    {
      anonymous_id: "F0RT",
      zip_code: "92105",
      has_pets: false,
      has_transport: false,
      medical_needs: true,
      can_volunteer: false,
      status: "Medical device power support",
      prep_score: 46,
    },
    {
      anonymous_id: "H5YW",
      zip_code: "92105",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: true,
      status: "Preparing",
      prep_score: 66,
    },
    {
      anonymous_id: "J8QC",
      zip_code: "92105",
      has_pets: true,
      has_transport: false,
      medical_needs: false,
      can_volunteer: false,
      status: "Needs ride",
      prep_score: 34,
    },
    {
      anonymous_id: "L2VB",
      zip_code: "92105",
      has_pets: false,
      has_transport: true,
      medical_needs: false,
      can_volunteer: false,
      status: "Safe",
      prep_score: 83,
    },
  ],
  needs: [
    { label: "Evacuation rides", count: 3 },
    { label: "Water delivery", count: 2 },
    { label: "Accessible shelter beds", count: 1 },
    { label: "Medical device power support", count: 2 },
    { label: "Pet transport", count: 2 },
    { label: "Translation help", count: 1 },
    { label: "Volunteer driver matches", count: 2 },
    { label: "Marked safe", count: 4 },
    { label: "Prescription pickup", count: 1 },
    { label: "Ice / cooling centers", count: 1 },
    { label: "Shelter info", count: 2 },
    { label: "Accessible evacuation rides", count: 1 },
    { label: "N95 / smoke masks", count: 2 },
  ],
  events: [
    {
      id: "92105-e1",
      message: "Household N3XP requested evacuation transport",
      timestamp: "2026-05-09T17:55:00.000Z",
    },
    {
      id: "92105-e2",
      message: "Household Q8WR marked safe",
      timestamp: "2026-05-09T17:20:00.000Z",
    },
    {
      id: "92105-e3",
      message: "Household V9KM requested medical device power support",
      timestamp: "2026-05-09T16:40:00.000Z",
    },
    {
      id: "92105-e4",
      message: "Household H5YW volunteered for neighborhood transport",
      timestamp: "2026-05-09T15:30:00.000Z",
    },
    {
      id: "92105-e5",
      message: "Household T2LS completed go-bag task",
      timestamp: "2026-05-09T14:15:00.000Z",
    },
    {
      id: "92105-e6",
      message: "Household X1HJ asked for shelter info",
      timestamp: "2026-05-08T20:00:00.000Z",
    },
  ],
  resources: mockCommunity91001.resources,
};

export const mockCommunitiesByZip: Record<string, CommunityDashboardData> = {
  "91001": mockCommunity91001,
  "92105": mockCommunity92105,
};
